### ISSUE TITLE
improvement : show some exemples

### ISSUE THREAD

**Issue by FredericLetellier** [NicolasLetellier/isometricks#2]
Very good improvement the possibility of changing color ! 

The tool is really cool, simple to use. But it's hard to imagine how to build with it.

It would be a good improvement to give examples of successful achievements, firstly to see that this tool can produce magnificent drawings, secondly to understand how to build them.

The example would be displayed directly in the canvas, and we could draw from the example rather than from scratch.

(If we push the idea further, we can imagine small pre-built forms, the most frequent, which we just add to his current work in the canvas.)

**Comment by NicolasLetellier** [comment]
Thanks for the comment Bro! :)

It was indeed necessary to give some examples to users, in order to see what's really an isometric illustration and to have some clues about how using the editor.

Now it's done! I've put homemade examples on the information page. I hope it can help.

Being able to load on the editor already made examples, or also previous works from the user, would be a great feature, but it would be a big project by itself and it's not on the road-map yet...
Well, I have to write the road-map too! :)
